name: Npm package

on:
  push:
    branches:
      - "*"
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Nodejs 10.16.3
        uses: actions/setup-node@master
        with:
          version: 10.16.3

      - name: Build
        run: |
          npm ci

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.2.1
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: npx jest --coverage

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: coverage
          path: ./coverage

      - name: Publish to Npm
        if: contains(github.ref, 'refs/tags/v')
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
